# Generated by Django 4.2 on 2025-10-26 22:13

import core.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=200, verbose_name="Nome")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Telefone"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aluno_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Aluno",
                "verbose_name_plural": "Alunos",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Treinamento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=200, verbose_name="Nome")),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Treinamento",
                "verbose_name_plural": "Treinamentos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Turma",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=200, verbose_name="Nome")),
                ("data_inicio", models.DateField(verbose_name="Data de Início")),
                ("data_conclusao", models.DateField(verbose_name="Data de Conclusão")),
                (
                    "link_acesso",
                    models.URLField(
                        blank=True, null=True, verbose_name="Link de Acesso"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "treinamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turmas",
                        to="core.treinamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Turma",
                "verbose_name_plural": "Turmas",
                "ordering": ["-data_inicio"],
            },
        ),
        migrations.CreateModel(
            name="Recurso",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo_recurso",
                    models.CharField(
                        choices=[
                            ("video", "Vídeo"),
                            ("arquivo_pdf", "Arquivo PDF"),
                            ("arquivo_zip", "Arquivo ZIP"),
                        ],
                        max_length=20,
                        verbose_name="Tipo do Recurso",
                    ),
                ),
                (
                    "acesso_previo",
                    models.BooleanField(default=False, verbose_name="Acesso Prévio"),
                ),
                ("draft", models.BooleanField(default=True, verbose_name="Rascunho")),
                (
                    "nome_recurso",
                    models.CharField(max_length=200, verbose_name="Nome do Recurso"),
                ),
                (
                    "descricao_recurso",
                    models.TextField(
                        blank=True, null=True, verbose_name="Descrição do Recurso"
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        upload_to=core.models.upload_to,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["mp4", "avi", "mov", "pdf", "zip"]
                            )
                        ],
                        verbose_name="Arquivo",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recursos",
                        to="core.turma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recurso",
                "verbose_name_plural": "Recursos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Matricula",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "data_matricula",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Matrícula"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matriculas",
                        to="core.aluno",
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matriculas",
                        to="core.turma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Matrícula",
                "verbose_name_plural": "Matrículas",
                "ordering": ["-data_matricula"],
                "unique_together": {("turma", "aluno")},
            },
        ),
    ]
