# Generated by Django 4.2.16 on 2025-10-29 17:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AreaConhecimento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nome da Área"
                    ),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "cor_hex",
                    models.CharField(
                        default="#3B82F6", max_length=7, verbose_name="Cor (Hex)"
                    ),
                ),
                (
                    "icone",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Ícone"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Área de Conhecimento",
                "verbose_name_plural": "Áreas de Conhecimento",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="NivelDificuldade",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Nome do Nível"
                    ),
                ),
                (
                    "valor_numerico",
                    models.IntegerField(unique=True, verbose_name="Valor Numérico"),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "cor_hex",
                    models.CharField(
                        default="#10B981", max_length=7, verbose_name="Cor (Hex)"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Nível de Dificuldade",
                "verbose_name_plural": "Níveis de Dificuldade",
                "ordering": ["valor_numerico"],
            },
        ),
        migrations.CreateModel(
            name="Topico",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome do Tópico"),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "palavras_chave",
                    models.JSONField(default=list, verbose_name="Palavras-chave"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "area_conhecimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topicos",
                        to="core.areaconhecimento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tópico",
                "verbose_name_plural": "Tópicos",
                "ordering": ["area_conhecimento__nome", "nome"],
                "unique_together": {("nome", "area_conhecimento")},
            },
        ),
        migrations.CreateModel(
            name="MetadadosTreinamento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "duracao_estimada_horas",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Duração Estimada (horas)",
                    ),
                ),
                (
                    "carga_horaria_semanal",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="Carga Horária Semanal Sugerida",
                    ),
                ),
                (
                    "objetivos_aprendizagem",
                    models.JSONField(
                        default=list, verbose_name="Objetivos de Aprendizagem"
                    ),
                ),
                (
                    "competencias_desenvolvidas",
                    models.JSONField(
                        default=list, verbose_name="Competências Desenvolvidas"
                    ),
                ),
                (
                    "relevancia_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                        verbose_name="Score de Relevância",
                    ),
                ),
                (
                    "popularidade_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                        verbose_name="Score de Popularidade",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "area_conhecimento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.areaconhecimento",
                    ),
                ),
                (
                    "nivel_dificuldade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.niveldificuldade",
                    ),
                ),
                (
                    "topicos",
                    models.ManyToManyField(
                        blank=True, to="core.topico", verbose_name="Tópicos Abordados"
                    ),
                ),
                (
                    "treinamento",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadados",
                        to="core.treinamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Metadados do Treinamento",
                "verbose_name_plural": "Metadados dos Treinamentos",
            },
        ),
        migrations.CreateModel(
            name="MetadadosRecurso",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "formato_conteudo",
                    models.CharField(
                        choices=[
                            ("video_aula", "Vídeo Aula"),
                            ("documento_pdf", "Documento PDF"),
                            ("apresentacao", "Apresentação"),
                            ("exercicio", "Exercício"),
                            ("avaliacao", "Avaliação"),
                            ("material_apoio", "Material de Apoio"),
                            ("codigo_fonte", "Código Fonte"),
                            ("dataset", "Dataset"),
                        ],
                        max_length=20,
                        verbose_name="Formato do Conteúdo",
                    ),
                ),
                (
                    "duracao_minutos",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Duração em Minutos",
                    ),
                ),
                (
                    "tempo_estimado_conclusao",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Tempo Estimado para Conclusão (min)",
                    ),
                ),
                (
                    "tipo_interatividade",
                    models.CharField(
                        choices=[
                            ("passivo", "Passivo (Leitura/Visualização)"),
                            ("interativo", "Interativo (Exercícios)"),
                            ("pratico", "Prático (Hands-on)"),
                            ("colaborativo", "Colaborativo (Grupo)"),
                        ],
                        default="passivo",
                        max_length=20,
                        verbose_name="Tipo de Interatividade",
                    ),
                ),
                (
                    "palavras_chave",
                    models.JSONField(default=list, verbose_name="Palavras-chave"),
                ),
                (
                    "ordem_sugerida",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Ordem Sugerida na Sequência",
                    ),
                ),
                (
                    "dependencias",
                    models.JSONField(
                        default=list, verbose_name="IDs de Recursos Dependentes"
                    ),
                ),
                (
                    "relevancia_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                        verbose_name="Score de Relevância",
                    ),
                ),
                (
                    "qualidade_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                        verbose_name="Score de Qualidade",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "nivel_dificuldade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.niveldificuldade",
                    ),
                ),
                (
                    "recurso",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadados",
                        to="core.recurso",
                    ),
                ),
                (
                    "topicos",
                    models.ManyToManyField(
                        blank=True, to="core.topico", verbose_name="Tópicos Específicos"
                    ),
                ),
            ],
            options={
                "verbose_name": "Metadados do Recurso",
                "verbose_name_plural": "Metadados dos Recursos",
            },
        ),
        migrations.CreateModel(
            name="PreRequisito",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("object_id_origem", models.UUIDField()),
                ("object_id_requisito", models.UUIDField()),
                (
                    "obrigatorio",
                    models.BooleanField(
                        default=True, verbose_name="Pré-requisito Obrigatório"
                    ),
                ),
                (
                    "peso",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Peso do Pré-requisito",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type_origem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prerequisitos_origem",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "content_type_requisito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prerequisitos_requisito",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pré-requisito",
                "verbose_name_plural": "Pré-requisitos",
                "unique_together": {
                    (
                        "content_type_origem",
                        "object_id_origem",
                        "content_type_requisito",
                        "object_id_requisito",
                    )
                },
            },
        ),
    ]
