# Generated by Django 4.2.16 on 2025-10-30 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_areaconhecimento_niveldificuldade_topico_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="metadadosrecurso",
            name="nivel_dificuldade",
        ),
        migrations.RemoveField(
            model_name="metadadosrecurso",
            name="recurso",
        ),
        migrations.RemoveField(
            model_name="metadadosrecurso",
            name="topicos",
        ),
        migrations.RemoveField(
            model_name="metadadostreinamento",
            name="area_conhecimento",
        ),
        migrations.RemoveField(
            model_name="metadadostreinamento",
            name="nivel_dificuldade",
        ),
        migrations.RemoveField(
            model_name="metadadostreinamento",
            name="topicos",
        ),
        migrations.RemoveField(
            model_name="metadadostreinamento",
            name="treinamento",
        ),
        migrations.AlterUniqueTogether(
            name="prerequisito",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="prerequisito",
            name="content_type_origem",
        ),
        migrations.RemoveField(
            model_name="prerequisito",
            name="content_type_requisito",
        ),
        migrations.AlterUniqueTogether(
            name="topico",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="topico",
            name="area_conhecimento",
        ),
        migrations.AddField(
            model_name="recurso",
            name="treinamento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recursos",
                to="core.treinamento",
            ),
        ),
        migrations.AlterField(
            model_name="recurso",
            name="turma",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recursos",
                to="core.turma",
            ),
        ),
        migrations.DeleteModel(
            name="AreaConhecimento",
        ),
        migrations.DeleteModel(
            name="MetadadosRecurso",
        ),
        migrations.DeleteModel(
            name="MetadadosTreinamento",
        ),
        migrations.DeleteModel(
            name="NivelDificuldade",
        ),
        migrations.DeleteModel(
            name="PreRequisito",
        ),
        migrations.DeleteModel(
            name="Topico",
        ),
    ]
