# Generated by Django 4.2.16 on 2025-10-31 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_add_treinamento_to_recurso"),
    ]

    operations = [
        migrations.AddField(
            model_name="treinamento",
            name="nivel",
            field=models.CharField(
                choices=[
                    ("iniciante", "Iniciante"),
                    ("intermediario", "Intermediário"),
                    ("avancado", "Avançado"),
                ],
                default="iniciante",
                max_length=20,
                verbose_name="Nível",
            ),
        ),
    ]
